# Generated by Django 5.2.8 on 2025-11-24 11:12

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.license_upload_to),
        ),
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='license',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=30, help_text='Send reminder this many days before expiry'),
        ),
        migrations.AddField(
            model_name='license',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
