# Generated by Django 5.2.8 on 2025-11-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_license_file_license_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reminders_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='reminders_sent',
            field=models.BooleanField(default=False),
        ),
    ]
