# Generated by Django 5.2.8 on 2026-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_adminsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=7, help_text='Send reminder this many days before expiry'),
        ),
        migrations.AlterField(
            model_name='license',
            name='notify_before_days',
            field=models.PositiveIntegerField(default=7, help_text='Send reminder this many days before expiry'),
        ),
    ]
