# Generated by Django 5.2.8 on 2026-01-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_certificate_notify_before_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reminder_stage',
            field=models.CharField(choices=[('NONE', 'None'), ('PRE', 'Pre-expiry'), ('ON', 'On expiry'), ('POST', 'Post expiry')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='license',
            name='reminder_stage',
            field=models.CharField(choices=[('NONE', 'None'), ('PRE', 'Pre-expiry'), ('ON', 'On expiry'), ('POST', 'Post expiry')], default='NONE', max_length=10),
        ),
    ]
